import time
segundos = int(input('Escolha o número da contagem: '))

for s in range(segundos,0, -1):
    print(s)
    time.sleep(1)
print('PATRALPAPATRAPAPATRATRAAALLLLLPAPAAPAPAPAPAPAPATRATRATRAAALLT')
print('RAALLTRATRAPTRAPATRAPAPATRAPOWPOWPOWFIIIILLLFIILFILFIIIIILLFILLL')
print('POWPOWPOWPOWPUUUUPUUUUPUUUUPAPAPAPAPOWPOWPOWTRATRATRAPAPOWPOWPULPUL')
print('PULPULPOWPOWFIIILLFILLLFILLLPOWPULPULVRAAAAALLLLLPOWPAPAFILPULPOW')